# Generated by Django 4.2.20 on 2025-04-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                    ("stuck", "Stuck"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
