# Generated by Django 4.2.20 on 2025-04-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_item_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="status",
            field=models.CharField(default="todo", max_length=20),
        ),
    ]
