# Generated by Django 4.2.20 on 2025-04-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationtemplate",
            name="default_conditions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional default conditions for this template.",
                null=True,
            ),
        ),
    ]
