# Generated by Django 4.2.20 on 2025-04-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_automationtemplate_default_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="automation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="automation",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
