# Generated by Django 4.2.20 on 2025-04-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_automation_description_automation_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="automation",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
